language: nix
nix: 2.3.2

before_script:
  - nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
  - nix-channel --update

jobs:
  include:
    - name:   "Check project itself"
      script: "nix-shell --run 'cargo test --all --verbose'"
    - name:   "Check default.nix"
      script: "nix-build ."
