[package]
authors = ["jD91mZM2 <me@krake.one>"]
edition = "2018"
name = "rnix-lsp"
version = "0.1.0"

[dependencies]
failure = "0.1.5"
lsp-types = "0.61.0"
rnix = "0.6.0"
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"
url = "2.1.0"
