[package]
authors = ["jD91mZM2 <me@krake.one>"]
edition = "2018"
name = "rnix-lsp"
version = "0.1.0"

[dependencies]
failure = "0.1.5"
lsp-types = "0.61.0"
# nixpkgs-fmt = { git = "https://github.com/nix-community/nixpkgs-fmt", rev = "..." }
nixpkgs-fmt = { path = "/home/user/Downloads/nixpkgs-fmt/" }
rnix = "0.6.0"
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"
url = "2.1.0"

[patch.crates-io]
rnix = { git = "https://github.com/nix-community/rnix-parser", rev = "032d580a17d0e924a1c105f2413b5e951019982b" }
