cargo-features = ["edition"]

[package]
name = "nix-lsp"
version = "0.1.0"
authors = ["jD91mZM2 <me@krake.one>"]
edition = "2018"

[dependencies]
failure = "0.1.2"
rnix = { path = "../rnix" }
#rnix = { git = "https://gitlab.com/jD91mZM2/rnix.git", branch = "errors" }
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.26"
