[package]
authors = ["jD91mZM2 <me@krake.one>"]
edition = "2018"
name = "nix-lsp"
version = "0.1.0"
[dependencies]
failure = "0.1.2"
serde = "1.0.71"
serde_derive = "1.0.74"
serde_json = "1.0.26"
url = "1.7.2"

[dependencies.rnix]
branch = "rowan"
git = "https://gitlab.com/jD91mZM2/rnix"

[dependencies.rowan]
git = "https://github.com/matklad/rowan"
